# Generated by Django 3.1 on 2020-08-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_auto_20200823_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinventory',
            name='buildDate',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
