# Generated by Django 3.1 on 2020-08-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_carinventory_builddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinventory',
            name='engineSize',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
